// AUTOGENERATED
// The original file is literate/readme.md

// PLEASE DO NOT EDIT THIS FILE DIRECTLY !


import { $BaseStore, $isUnfrozenObject, $Cache } from './1-base-store';
let result = { $BaseStore, $isUnfrozenObject, $Cache };
export { result };