// Some test data - yes this was generated by ai.

let data1 = { data: null };
let data2 = { data: undefined };

let data3 = [1, 2, 3];
data3.push(data3);

let data4 = { value: 'abc' };
data4.self = data4;

let data5 = { a: [1, 2, 3] };
data5.b = { c: data5 };

let data6 = { x: { y: { z: {} } } };
data6.x.y.z = data6;

let data7 = { prop: 'value1' };
data7.child = { prop: 'value2' };
data7.child.parent = data7;

let data8 = [1, 2, 3];
data8.push(data8);
data8.push([4, 5, data8]);

let data9 = { a: { b: { c: {} } } };
data9.a.b.c = data9;
data9.a.b.c.d = { e: data9.a.b.c };

let data10 = [1, [2, [3, [4, [5, [6]]]]]];
data10[1][1][1][1][1] = data10;

let data11 = {
  prop1: [1, 2, 3],
  prop2: { nested: { prop3: 'abc' } },
};
data11.prop2.self = data11;

let data12 = { a: [1, 2, 3] };
data12.b = { c: { d: data12 } };
data12.b.c.self = data12.b.c;

let data13 = { x: [1, 2, 3], y: { z: { w: { v: [] } } } };
let v = data13.y.z.w.v;
v.push(data13);
v.push({ prop: 'Value', self: v });

let data14 = { prop1: { prop2: { prop3: {} } } };
data14.prop1.prop2.prop3.data = data14;
data14.prop1.prop2.prop3.arr = [1, 2, data14.prop1.prop2.prop3];

let data15 = { a: { b: { c: {} } } };
data15.a.b.c.d = { e: { f: { g: { h: data15 } } } };
data15.a.b.c.d.e.f.g.h.i = [data15.a.b.c, data15.a.b.c.d.e.f.g.h];

let data16 = { prop1: 'value1', prop2: null, prop3: {} };
data16.prop3.self = data16.prop3;
data16.prop3.nested = { prop4: [data16, data16.prop3] };

let data17 = { a: { b: { c: {} } } };
let a = data17.a;
a.b.c = data17;
a.b.d = { e: { f: a.b } };

let data18 = { a: { b: { c: {} } }, abc: undefined };
let c = data18.a.b.c;
c = data18.a;
c.d = { e: { f: { g: { h: { i: data18 } } } } };

let data19 = { list: [] };
let node = { value: 'Node 1' };
node.next = node;
let list = data19.list;
list.push(node);
list.push({ value: 'Node 2', next: list[0] });
