version: "3"
services:
  express:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: express.Dockerfile
    container_name: btld-express-server
    ports:
      - "4000:4000"
    volumes:
      - ~/btld-web/src/server/:/usr/app/server
    command: npm run express
