version: "3.1"
services:
  express:
    build:
      context: .
      dockerfile: node.Dockerfile
    container_name: btld-web-express
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ~/btld-web/@btld-web/server/:/usr/app/project
    command: npm run express
    networks:
      - server-net
    secrets:
      - MAIL_APP_PW
  hocuspocus:
    build:
      context: .
      dockerfile: node.Dockerfile
    container_name: btld-web-hocuspocus
    ports:
      - "127.0.0.1:4001:4001"
    volumes:
      - ~/btld-web/@btld-web/server/:/usr/app/project
    command: npm run hocuspocus
    networks:
      - server-net
  build-editor:
    build:
      context: ../..
      dockerfile: ./@btld-web/server/node.Dockerfile
    container_name: btld-web-build-editor
    volumes:
      - ~/btld-web/:/usr/app/project
    command: npm run build-editor
networks:
  server-net:
    external:
      name: install_default
secrets:
  MAIL_APP_PW:
    file: ~/.install/secrets/MAIL_APP_PW.txt
