version: "3"
services:
  express:
    build:
      context: .
      dockerfile: node.Dockerfile
    container_name: btld-web-express
    ports:
      - "4000:4000"
    volumes:
      - ~/btld-web/@btld-web/server/:/usr/app/server
    command: npm run express
  hocuspocus:
    build:
      context: .
      dockerfile: node.Dockerfile
    container_name: btld-web-hocuspocus
    ports:
      - "4001:4001"
    volumes:
      - ~/btld-web/@btld-web/server/:/usr/app/server
    command: npm run hocuspocus
  build-editor:
    build:
      context: ../..
      dockerfile: ./@btld-web/server/node.Dockerfile
    container_name: btld-web-build-editor
    volumes:
      - ~/btld-web/:/usr/app/project
    command: npm run build-editor
