version: "3.7"
services:
  express:
    container_name: btld-web-express
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ~/btld-web/:/project
    command: npm run express -w @btld-web/server
    networks:
      - server-net
    secrets:
      - MAIL_APP_PW
      - CLOUDFLARE_EMAIL
      - CLOUDFLARE_KEY
      - CLOUDFLARE_ZONE
  hocuspocus:
    container_name: btld-web-hocuspocus
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - "127.0.0.1:4001:4001"
    volumes:
      - ~/btld-web/:/project
    command: npm run hocuspocus -w @btld-web/server
    networks:
      - server-net
  build-editor:
    container_name: btld-web-build
    build:
      context: .
      dockerfile: node.Dockerfile
    volumes:
      - ~/btld-web/:/project
    command:
      - /bin/sh
      - -c
      - |
        git pull
        npm install
        npm run build -w @btld-web/editor
  pg-database:
    container_name: btld-web-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
	  volumes:
      - /data/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  pg-admin:
    container_name: btld-web-db-admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
	volumes:
      - /data/pg_admin:/var/lib/pgadmin
networks:
  server-net:
    external:
      name: install_default
secrets:
  MAIL_APP_PW:
    file: ~/.install/secrets/MAIL_APP_PW.txt
  CLOUDFLARE_EMAIL:
    file: ~/.install/secrets/CLOUDFLARE_EMAIL.txt
  CLOUDFLARE_KEY:
    file: ~/.install/secrets/CLOUDFLARE_KEY.txt
  CLOUDFLARE_ZONE:
    file: ~/.install/secrets/CLOUDFLARE_ZONE.txt
