version: "3.7"
services:
  express:
    container_name: btld-web-express
    image: timbru31/node-alpine-git:20
    restart: always
    ports:
      - "433:433"
    working_dir: /data/btld-web
    volumes:
      - /data/btld-web:/data/btld-web
      - /data/server:/data/server
    env_file:
      - /data/config.env
    command: npm run express -w @btld-web/server
    networks:
      - btld-net
  couchdb:
    container_name: btld-web-couchdb
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    volumes:
      - /data/couchdb:/opt/couchdb/data
    env_file:
      - /data/config.env
    networks:
      - btld-net
networks:
  btld-net:
    driver: bridge
    name: btld-net
